# Generated by Django 4.2 on 2024-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
    ]
