# Generated by Django 4.2 on 2024-03-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço Anterior'),
        ),
    ]
