# Generated by Django 4.2 on 2024-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_real_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='real_price',
        ),
        migrations.AddField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço Anterior'),
        ),
    ]
