# Generated by Django 4.2 on 2024-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderitem_real_price_product_full_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_price',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço'),
        ),
    ]
