# Generated by Django 4.2 on 2024-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_full_price_product_promotion_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='line',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço De'),
        ),
    ]
