# Generated by Django 4.2 on 2024-02-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_upload',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
    ]
