# Generated by Django 4.2 on 2024-03-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_line_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotion_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_before',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço De'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço'),
        ),
    ]
