# Generated by Django 4.2 on 2024-03-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_promotion_price_product_price_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço do Pediido'),
        ),
    ]
