# Generated by Django 4.2 on 2024-03-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Preço do Pediido'),
        ),
    ]
