# Generated by Django 4.2 on 2024-03-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Valor do Pedido'),
        ),
    ]
