# Generated by Django 4.2 on 2024-03-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_price',
        ),
    ]
