# Generated by Django 4.2 on 2024-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_orderitem_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_product',
            field=models.IntegerField(default=1, verbose_name='Quant. Produto'),
        ),
    ]
