# Generated by Django 4.2 on 2024-03-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
