# Generated by Django 4.2 on 2024-03-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado Em'),
        ),
    ]
