# Generated by Django 4.2 on 2024-02-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_image'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcart',
            unique_together={('cart_key', 'product')},
        ),
    ]
