# Generated by Django 4.2 on 2024-03-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_itemcart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
